### ISSUE TITLE
Revisar

### ISSUE THREAD

**Issue by barbosa92** [Jnv821/4Geeks-Forms#1]
- [ ] Revisa que los inputs del tipo de tarjeta se muestren bien

**Comment by Jnv821** [comment]
Los inputs del tipo de tarjeta ha sido cambiado para acomodar de forma vertical correctamente a todas las tarjetas en displays de menor tamaño. 

Al mismo tiempo se ha añadido un margen y padding más uniforme a todos los elementos para los inputs de tipo tarjeta.
